-- Private content schema for lzxszty.
-- Replace the two email placeholders near the top before running this script.

create table if not exists public.love_allowed_users (
	email text primary key,
	cat_id text,
	created_at timestamptz not null default now()
);

alter table public.love_allowed_users
add column if not exists cat_id text;

insert into public.love_allowed_users (email, cat_id)
values
	(lower('black@cat.com'), 'black'),
	(lower('white@cat.com'), 'white')
on conflict (email) do update
set cat_id = excluded.cat_id;

alter table public.love_allowed_users enable row level security;
revoke all on public.love_allowed_users from anon, authenticated;

create or replace function public.love_is_allowed_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
	select exists (
		select 1
		from public.love_allowed_users
		where email = lower(coalesce(auth.jwt() ->> 'email', ''))
	);
$$;

grant execute on function public.love_is_allowed_user() to anon, authenticated;

create or replace function public.love_current_cat()
returns text
language sql
stable
security definer
set search_path = public
as $$
	select cat_id
	from public.love_allowed_users
	where email = lower(coalesce(auth.jwt() ->> 'email', ''))
	limit 1;
$$;

grant execute on function public.love_current_cat() to anon, authenticated;

create table if not exists public.love_home (
	id text primary key default 'main',
	eyebrow text,
	title text,
	lead text,
	hero_image_path text,
	updated_at timestamptz not null default now(),
	constraint love_home_singleton check (id = 'main')
);

create table if not exists public.love_cats (
	id text primary key,
	name text not null,
	mood integer not null default 50,
	affection integer not null default 50,
	updated_at timestamptz not null default now(),
	constraint love_cats_id check (id in ('black', 'white')),
	constraint love_cats_mood check (mood between 0 and 100),
	constraint love_cats_affection check (affection between 0 and 100)
);

insert into public.love_cats (id, name)
values
	('black', '黑色小猫'),
	('white', '白色小猫')
on conflict (id) do update
set name = excluded.name;

create table if not exists public.love_posts (
	slug text primary key,
	title text not null,
	summary text,
	body text,
	tags text[] not null default '{}',
	author text references public.love_cats(id) on delete set null,
	hero_image_path text,
	like_count bigint not null default 0,
	comment_count bigint not null default 0,
	published_at date not null default current_date,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

alter table public.love_posts
add column if not exists author text references public.love_cats(id) on delete set null;

alter table public.love_posts
add column if not exists hero_image_path text;

alter table public.love_posts
add column if not exists like_count bigint not null default 0;

alter table public.love_posts
add column if not exists comment_count bigint not null default 0;

create table if not exists public.love_meow_messages (
	id bigint generated by default as identity primary key,
	author text not null references public.love_cats(id) on delete cascade,
	body text not null,
	created_at timestamptz not null default now()
);

create table if not exists public.love_stats (
	id text primary key,
	label text not null,
	value text,
	suffix text not null default '',
	size text not null default 'medium',
	mode text,
	target_date date,
	sort_order integer not null default 0,
	updated_at timestamptz not null default now(),
	constraint love_stats_size check (size in ('small', 'medium', 'large')),
	constraint love_stats_mode check (mode is null or mode in ('since', 'until'))
);

create table if not exists public.love_timeline_events (
	id bigint generated by default as identity primary key,
	event_date date not null,
	title text not null,
	body text,
	post_slug text references public.love_posts(slug) on delete set null,
	importance text not null default 'medium',
	image_path text,
	sort_order integer not null default 0,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	constraint love_timeline_importance check (importance in ('small', 'medium', 'large'))
);

create table if not exists public.love_gallery_items (
	id bigint generated by default as identity primary key,
	slug text,
	title text not null,
	body text,
	image_path text,
	captured_at date,
	size text not null default 'medium',
	sort_order integer not null default 0,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	constraint love_gallery_size check (size in ('medium', 'large'))
);

alter table public.love_gallery_items
add column if not exists slug text;

create unique index if not exists love_gallery_items_slug_idx
on public.love_gallery_items (slug);

create table if not exists public.love_about_sections (
	id text primary key,
	title text not null,
	body text,
	section_type text not null default 'text',
	sort_order integer not null default 0,
	updated_at timestamptz not null default now()
);

create table if not exists public.love_achievements (
	id text primary key,
	title text not null,
	body text,
	state text,
	sort_order integer not null default 0,
	updated_at timestamptz not null default now()
);

create table if not exists public.love_games (
	id text primary key,
	title text not null,
	body text,
	sort_order integer not null default 0,
	updated_at timestamptz not null default now()
);

alter table public.love_home enable row level security;
alter table public.love_posts enable row level security;
alter table public.love_cats enable row level security;
alter table public.love_meow_messages enable row level security;
alter table public.love_stats enable row level security;
alter table public.love_timeline_events enable row level security;
alter table public.love_gallery_items enable row level security;
alter table public.love_about_sections enable row level security;
alter table public.love_achievements enable row level security;
alter table public.love_games enable row level security;

grant usage on schema public to authenticated;
grant select on
	public.love_home,
	public.love_posts,
	public.love_cats,
	public.love_meow_messages,
	public.love_stats,
	public.love_timeline_events,
	public.love_gallery_items,
	public.love_about_sections,
	public.love_achievements,
	public.love_games
to authenticated;

drop policy if exists "allowed users can read home" on public.love_home;
drop policy if exists "allowed users can read posts" on public.love_posts;
drop policy if exists "allowed users can read cats" on public.love_cats;
drop policy if exists "allowed users can read meow messages" on public.love_meow_messages;
drop policy if exists "allowed users can read stats" on public.love_stats;
drop policy if exists "allowed users can read timeline events" on public.love_timeline_events;
drop policy if exists "allowed users can read gallery items" on public.love_gallery_items;
drop policy if exists "allowed users can read about sections" on public.love_about_sections;
drop policy if exists "allowed users can read achievements" on public.love_achievements;
drop policy if exists "allowed users can read games" on public.love_games;

create policy "allowed users can read home"
on public.love_home for select
to authenticated
using (public.love_is_allowed_user());

create policy "allowed users can read posts"
on public.love_posts for select
to authenticated
using (public.love_is_allowed_user());

create policy "allowed users can read cats"
on public.love_cats for select
to authenticated
using (public.love_is_allowed_user());

create policy "allowed users can read meow messages"
on public.love_meow_messages for select
to authenticated
using (public.love_is_allowed_user());

create policy "allowed users can read stats"
on public.love_stats for select
to authenticated
using (public.love_is_allowed_user());

create policy "allowed users can read timeline events"
on public.love_timeline_events for select
to authenticated
using (public.love_is_allowed_user());

create policy "allowed users can read gallery items"
on public.love_gallery_items for select
to authenticated
using (public.love_is_allowed_user());

create policy "allowed users can read about sections"
on public.love_about_sections for select
to authenticated
using (public.love_is_allowed_user());

create policy "allowed users can read achievements"
on public.love_achievements for select
to authenticated
using (public.love_is_allowed_user());

create policy "allowed users can read games"
on public.love_games for select
to authenticated
using (public.love_is_allowed_user());

create or replace function public.love_perform_cat_action(action_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	actor_cat text;
	target_cat text;
	mood_delta integer;
	affection_delta integer;
	updated_cat jsonb;
begin
	actor_cat := public.love_current_cat();

	if actor_cat is null then
		raise exception 'not allowed';
	end if;

	if action_name = 'feed' then
		target_cat := case when actor_cat = 'black' then 'white' else 'black' end;
		mood_delta := 8;
		affection_delta := 6;
	elsif action_name = 'meow' then
		target_cat := actor_cat;
		mood_delta := 5;
		affection_delta := 4;
	else
		raise exception 'unknown action';
	end if;

	update public.love_cats
	set mood = least(100, mood + mood_delta),
		affection = least(100, affection + affection_delta),
		updated_at = now()
	where id = target_cat
	returning to_jsonb(public.love_cats.*) into updated_cat;

	return updated_cat;
end;
$$;

create or replace function public.love_add_meow_message(message_body text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	actor_cat text;
	clean_body text;
	inserted_message jsonb;
begin
	actor_cat := public.love_current_cat();
	clean_body := trim(coalesce(message_body, ''));

	if actor_cat is null then
		raise exception 'not allowed';
	end if;

	if clean_body = '' then
		raise exception 'message is empty';
	end if;

	insert into public.love_meow_messages (author, body)
	values (actor_cat, clean_body)
	returning to_jsonb(public.love_meow_messages.*) into inserted_message;

	return inserted_message;
end;
$$;

create or replace function public.love_save_post(
	post_slug text,
	post_title text,
	post_summary text,
	post_body text,
	post_tags text[] default '{}',
	post_hero_image_path text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	actor_cat text;
	clean_slug text;
	clean_title text;
	existing_author text;
	post_exists boolean;
	saved_post jsonb;
begin
	actor_cat := public.love_current_cat();
	clean_slug := lower(trim(coalesce(post_slug, '')));
	clean_slug := regexp_replace(clean_slug, '[^a-z0-9-]+', '-', 'g');
	clean_slug := regexp_replace(clean_slug, '-+', '-', 'g');
	clean_slug := trim(both '-' from clean_slug);
	clean_title := trim(coalesce(post_title, ''));

	if actor_cat is null then
		raise exception 'not allowed';
	end if;

	if clean_slug = '' then
		raise exception 'post slug is empty';
	end if;

	if clean_title = '' then
		raise exception 'post title is empty';
	end if;

	select author
	into existing_author
	from public.love_posts
	where slug = clean_slug;
	post_exists := found;

	if post_exists then
		if existing_author is distinct from actor_cat then
			raise exception 'only the author can edit this post';
		end if;

		update public.love_posts
		set title = clean_title,
			summary = nullif(trim(coalesce(post_summary, '')), ''),
			body = coalesce(post_body, ''),
			tags = coalesce(post_tags, '{}'),
			hero_image_path = nullif(trim(coalesce(post_hero_image_path, '')), ''),
			updated_at = now()
		where slug = clean_slug
		returning to_jsonb(public.love_posts.*) into saved_post;
	else
		insert into public.love_posts (
			slug,
			title,
			summary,
			body,
			tags,
			author,
			hero_image_path,
			published_at
		)
		values (
			clean_slug,
			clean_title,
			nullif(trim(coalesce(post_summary, '')), ''),
			coalesce(post_body, ''),
			coalesce(post_tags, '{}'),
			actor_cat,
			nullif(trim(coalesce(post_hero_image_path, '')), ''),
			current_date
		)
		returning to_jsonb(public.love_posts.*) into saved_post;
	end if;

	return saved_post;
end;
$$;

create or replace function public.love_delete_post(post_slug text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
	actor_cat text;
	existing_author text;
	clean_slug text;
begin
	actor_cat := public.love_current_cat();
	clean_slug := lower(trim(coalesce(post_slug, '')));

	if actor_cat is null then
		raise exception 'not allowed';
	end if;

	select author
	into existing_author
	from public.love_posts
	where slug = clean_slug;

	if not found then
		raise exception 'post not found';
	end if;

	if existing_author is distinct from actor_cat then
		raise exception 'only the author can delete this post';
	end if;

	delete from public.love_posts
	where slug = clean_slug;

	return clean_slug;
end;
$$;

create or replace function public.love_save_stat(
	stat_id text,
	left_text text default '',
	right_text text default '',
	stat_sort_order integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	actor_cat text;
	clean_id text;
	clean_left text;
	clean_right text;
	next_order integer;
	saved_stat jsonb;
begin
	actor_cat := public.love_current_cat();
	clean_id := lower(trim(coalesce(stat_id, '')));
	clean_id := regexp_replace(clean_id, '[^a-z0-9-]+', '-', 'g');
	clean_id := regexp_replace(clean_id, '-+', '-', 'g');
	clean_id := trim(both '-' from clean_id);
	clean_left := regexp_replace(trim(coalesce(left_text, '')), '[\r\n]+', ' ', 'g');
	clean_right := regexp_replace(trim(coalesce(right_text, '')), '[\r\n]+', ' ', 'g');

	if actor_cat is null then
		raise exception 'not allowed';
	end if;

	if clean_id = '' then
		raise exception 'stat id is empty';
	end if;

	if stat_sort_order is null then
		select coalesce(max(sort_order), 0) + 10
		into next_order
		from public.love_stats;
	else
		next_order := stat_sort_order;
	end if;

	insert into public.love_stats (
		id,
		label,
		value,
		suffix,
		size,
		mode,
		target_date,
		sort_order
	)
	values (
		clean_id,
		clean_left,
		'0',
		clean_right,
		'medium',
		null,
		null,
		next_order
	)
	on conflict (id) do update
	set label = excluded.label,
		suffix = excluded.suffix,
		sort_order = excluded.sort_order,
		updated_at = now()
	returning to_jsonb(public.love_stats.*) into saved_stat;

	return saved_stat;
end;
$$;

create or replace function public.love_set_stat(
	stat_id text,
	left_text text default '',
	right_text text default '',
	stat_value bigint default 0,
	stat_sort_order integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	actor_cat text;
	clean_id text;
	clean_left text;
	clean_right text;
	next_order integer;
	saved_stat jsonb;
begin
	actor_cat := public.love_current_cat();
	clean_id := lower(trim(coalesce(stat_id, '')));
	clean_id := regexp_replace(clean_id, '[^a-z0-9-]+', '-', 'g');
	clean_id := regexp_replace(clean_id, '-+', '-', 'g');
	clean_id := trim(both '-' from clean_id);
	clean_left := regexp_replace(trim(coalesce(left_text, '')), '[\r\n]+', ' ', 'g');
	clean_right := regexp_replace(trim(coalesce(right_text, '')), '[\r\n]+', ' ', 'g');

	if actor_cat is null then
		raise exception 'not allowed';
	end if;

	if clean_id = '' then
		raise exception 'stat id is empty';
	end if;

	if stat_sort_order is null then
		select coalesce(max(sort_order), 0) + 10
		into next_order
		from public.love_stats;
	else
		next_order := stat_sort_order;
	end if;

	insert into public.love_stats (
		id,
		label,
		value,
		suffix,
		size,
		mode,
		target_date,
		sort_order
	)
	values (
		clean_id,
		clean_left,
		greatest(0::bigint, coalesce(stat_value, 0))::text,
		clean_right,
		'medium',
		null,
		null,
		next_order
	)
	on conflict (id) do update
	set label = excluded.label,
		value = excluded.value,
		suffix = excluded.suffix,
		mode = null,
		target_date = null,
		sort_order = excluded.sort_order,
		updated_at = now()
	returning to_jsonb(public.love_stats.*) into saved_stat;

	return saved_stat;
end;
$$;

create or replace function public.love_adjust_stat(stat_id text, delta_value integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	actor_cat text;
	clean_id text;
	current_value bigint;
	new_value bigint;
	saved_stat jsonb;
begin
	actor_cat := public.love_current_cat();
	clean_id := lower(trim(coalesce(stat_id, '')));

	if actor_cat is null then
		raise exception 'not allowed';
	end if;

	select case
		when coalesce(value, '') ~ '^\d+$' then value::bigint
		else 0
	end
	into current_value
	from public.love_stats
	where id = clean_id;

	if not found then
		raise exception 'stat not found';
	end if;

	new_value := greatest(0, current_value + coalesce(delta_value, 0));

	update public.love_stats
	set value = new_value::text,
		mode = null,
		target_date = null,
		updated_at = now()
	where id = clean_id
	returning to_jsonb(public.love_stats.*) into saved_stat;

	return saved_stat;
end;
$$;

create or replace function public.love_delete_stat(stat_id text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
	actor_cat text;
	clean_id text;
begin
	actor_cat := public.love_current_cat();
	clean_id := lower(trim(coalesce(stat_id, '')));

	if actor_cat is null then
		raise exception 'not allowed';
	end if;

	delete from public.love_stats
	where id = clean_id;

	if not found then
		raise exception 'stat not found';
	end if;

	return clean_id;
end;
$$;

revoke execute on function public.love_perform_cat_action(text) from anon;
revoke execute on function public.love_add_meow_message(text) from anon;
revoke execute on function public.love_save_post(text, text, text, text, text[], text) from anon;
revoke execute on function public.love_delete_post(text) from anon;
revoke execute on function public.love_save_stat(text, text, text, integer) from anon;
revoke execute on function public.love_set_stat(text, text, text, bigint, integer) from anon;
revoke execute on function public.love_adjust_stat(text, integer) from anon;
revoke execute on function public.love_delete_stat(text) from anon;
grant execute on function public.love_perform_cat_action(text) to authenticated;
grant execute on function public.love_add_meow_message(text) to authenticated;
grant execute on function public.love_save_post(text, text, text, text, text[], text) to authenticated;
grant execute on function public.love_delete_post(text) to authenticated;
grant execute on function public.love_save_stat(text, text, text, integer) to authenticated;
grant execute on function public.love_set_stat(text, text, text, bigint, integer) to authenticated;
grant execute on function public.love_adjust_stat(text, integer) to authenticated;
grant execute on function public.love_delete_stat(text) to authenticated;

-- Private image/file bucket. Store private images here instead of public/.
insert into storage.buckets (id, name, public)
values ('love-private', 'love-private', false)
on conflict (id) do update set public = false;

drop policy if exists "allowed users can read love private files" on storage.objects;
drop policy if exists "allowed users can upload love private files" on storage.objects;
drop policy if exists "allowed users can update love private files" on storage.objects;
drop policy if exists "allowed users can delete love private files" on storage.objects;

create policy "allowed users can read love private files"
on storage.objects for select
to authenticated
using (
	bucket_id = 'love-private'
	and public.love_is_allowed_user()
);

create policy "allowed users can upload love private files"
on storage.objects for insert
to authenticated
with check (
	bucket_id = 'love-private'
	and public.love_is_allowed_user()
	and (
		name like 'posts/%'
		or name like 'drafts/%'
		or name like 'gallery/%'
	)
);

create policy "allowed users can update love private files"
on storage.objects for update
to authenticated
using (
	bucket_id = 'love-private'
	and public.love_is_allowed_user()
)
with check (
	bucket_id = 'love-private'
	and public.love_is_allowed_user()
);

create policy "allowed users can delete love private files"
on storage.objects for delete
to authenticated
using (
	bucket_id = 'love-private'
	and public.love_is_allowed_user()
);

do $$
begin
	alter publication supabase_realtime add table public.love_posts;
exception
	when duplicate_object then null;
end $$;

do $$
begin
	alter publication supabase_realtime add table public.love_stats;
exception
	when duplicate_object then null;
end $$;

do $$
begin
	alter publication supabase_realtime add table public.love_cats;
exception
	when duplicate_object then null;
end $$;

do $$
begin
	alter publication supabase_realtime add table public.love_gallery_items;
exception
	when duplicate_object then null;
end $$;

do $$
begin
	alter publication supabase_realtime add table public.love_meow_messages;
exception
	when duplicate_object then null;
end $$;
